// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the lottery module's genesis state.
type GenesisState struct {
	Params           Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Round            *Round            `protobuf:"bytes,2,opt,name=round,proto3" json:"round,omitempty"`
	TxnCounter       *TxnCounter       `protobuf:"bytes,3,opt,name=txnCounter,proto3" json:"txnCounter,omitempty"`
	BetList          []Bet             `protobuf:"bytes,4,rep,name=betList,proto3" json:"betList"`
	ValidatorsWinner *ValidatorsWinner `protobuf:"bytes,5,opt,name=validatorsWinner,proto3" json:"validatorsWinner,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee49847bb280688d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRound() *Round {
	if m != nil {
		return m.Round
	}
	return nil
}

func (m *GenesisState) GetTxnCounter() *TxnCounter {
	if m != nil {
		return m.TxnCounter
	}
	return nil
}

func (m *GenesisState) GetBetList() []Bet {
	if m != nil {
		return m.BetList
	}
	return nil
}

func (m *GenesisState) GetValidatorsWinner() *ValidatorsWinner {
	if m != nil {
		return m.ValidatorsWinner
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "karthik340.game.lottery.GenesisState")
}

func init() { proto.RegisterFile("lottery/genesis.proto", fileDescriptor_ee49847bb280688d) }

var fileDescriptor_ee49847bb280688d = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4e, 0x3a, 0x31,
	0x14, 0xc5, 0x67, 0xf8, 0xfa, 0x27, 0xe5, 0xbf, 0xd0, 0x11, 0xe3, 0x48, 0x4c, 0x21, 0xba, 0x41,
	0x17, 0x33, 0x06, 0x58, 0xea, 0x06, 0x4c, 0xdc, 0xb8, 0x30, 0xe3, 0x57, 0xe2, 0x86, 0x74, 0xa0,
	0x19, 0x1a, 0xa0, 0x25, 0x9d, 0x8b, 0xc2, 0x5b, 0xf8, 0x58, 0x2c, 0x59, 0xba, 0xd1, 0x18, 0x78,
	0x11, 0x43, 0xa7, 0x05, 0xa3, 0x99, 0x5d, 0x73, 0x7a, 0x7e, 0xa7, 0xa7, 0xf7, 0xa2, 0xfd, 0xa1,
	0x00, 0xa0, 0x72, 0xe6, 0x47, 0x94, 0xd3, 0x98, 0xc5, 0xde, 0x58, 0x0a, 0x10, 0xce, 0xc1, 0x80,
	0x48, 0xe8, 0xb3, 0x41, 0xa3, 0x79, 0xee, 0x45, 0x64, 0x44, 0x3d, 0x6d, 0x2b, 0x97, 0x22, 0x11,
	0x09, 0xe5, 0xf1, 0xd7, 0xa7, 0xc4, 0x5e, 0x2e, 0x99, 0x94, 0x31, 0x91, 0x64, 0xa4, 0x43, 0xca,
	0x7b, 0x46, 0x95, 0x62, 0xc2, 0x7b, 0x5a, 0x3c, 0x34, 0x22, 0x4c, 0x79, 0xa7, 0x2b, 0x26, 0x1c,
	0xa8, 0xd4, 0x57, 0xbb, 0xe6, 0x2a, 0xa4, 0xa0, 0xa5, 0x8a, 0x91, 0x5e, 0xc8, 0x90, 0xf5, 0x08,
	0x08, 0x19, 0x77, 0x5e, 0x19, 0xe7, 0x86, 0x39, 0xfe, 0xc8, 0xa0, 0xff, 0xd7, 0x49, 0xf5, 0x3b,
	0x20, 0x40, 0x9d, 0x4b, 0x54, 0x48, 0x4a, 0xb8, 0x76, 0xd5, 0xae, 0x15, 0xeb, 0x15, 0x2f, 0xe5,
	0x2b, 0xde, 0xad, 0xb2, 0xb5, 0x72, 0xf3, 0xcf, 0x8a, 0x15, 0x68, 0xc8, 0x69, 0xa2, 0xbc, 0x6a,
	0xeb, 0x66, 0x14, 0x8d, 0x53, 0xe9, 0x60, 0xed, 0x0a, 0x12, 0xb3, 0xd3, 0x46, 0x08, 0xa6, 0xbc,
	0x9d, 0xfc, 0xc6, 0xcd, 0x2a, 0xf4, 0x24, 0x15, 0xbd, 0xdf, 0x58, 0x83, 0x1f, 0x98, 0x73, 0x81,
	0xfe, 0x85, 0x14, 0x6e, 0x58, 0x0c, 0x6e, 0xae, 0x9a, 0xad, 0x15, 0xeb, 0x47, 0xa9, 0x09, 0x2d,
	0x0a, 0xba, 0xb7, 0x41, 0x9c, 0x07, 0xb4, 0xb3, 0x9d, 0xd1, 0x93, 0x1a, 0x91, 0x9b, 0x57, 0x45,
	0x4e, 0x53, 0x63, 0x1e, 0x7f, 0x01, 0xc1, 0x9f, 0x88, 0xd6, 0xd5, 0x7c, 0x89, 0xed, 0xc5, 0x12,
	0xdb, 0x5f, 0x4b, 0x6c, 0xbf, 0xad, 0xb0, 0xb5, 0x58, 0x61, 0xeb, 0x7d, 0x85, 0xad, 0xe7, 0xb3,
	0x88, 0x41, 0x7f, 0x12, 0x7a, 0x5d, 0x31, 0xf2, 0xb7, 0x0f, 0xf8, 0xeb, 0x07, 0xfc, 0xa9, 0xbf,
	0xd9, 0xf2, 0x6c, 0x4c, 0xe3, 0xb0, 0xa0, 0x96, 0xd5, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0x31, 0x63, 0x01, 0x6e, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidatorsWinner != nil {
		{
			size, err := m.ValidatorsWinner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BetList) > 0 {
		for iNdEx := len(m.BetList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BetList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.TxnCounter != nil {
		{
			size, err := m.TxnCounter.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Round != nil {
		{
			size, err := m.Round.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Round != nil {
		l = m.Round.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.TxnCounter != nil {
		l = m.TxnCounter.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.BetList) > 0 {
		for _, e := range m.BetList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ValidatorsWinner != nil {
		l = m.ValidatorsWinner.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Round == nil {
				m.Round = &Round{}
			}
			if err := m.Round.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxnCounter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxnCounter == nil {
				m.TxnCounter = &TxnCounter{}
			}
			if err := m.TxnCounter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BetList = append(m.BetList, Bet{})
			if err := m.BetList[len(m.BetList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsWinner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidatorsWinner == nil {
				m.ValidatorsWinner = &ValidatorsWinner{}
			}
			if err := m.ValidatorsWinner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
