accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: client1
    coins: ["500token"]
  - name: client2
    coins: ["500token"]
  - name: client3
    coins: ["500token"]
  - name: client4
    coins: ["500token"]
  - name: client5
    coins: ["500token"]
  - name: client6
    coins: ["500token"]
  - name: client7
    coins: ["500token"]
  - name: client8
    coins: ["500token"]
  - name: client9
    coins: ["500token"]
  - name: client10
    coins: ["500token"]
  - name: client11
    coins: ["500token"]
  - name: client12
    coins: ["500token"]
  - name: client13
    coins: ["500token"]
  - name: client14
    coins: ["500token"]
  - name: client15
    coins: ["500token"]
  - name: client16
    coins: ["500token"]
  - name: client17
    coins: ["500token"]
  - name: client18
    coins: ["500token"]
  - name: client19
    coins: ["500token"]
  - name: client20
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  config:
    consensus:
      timeout_commit: "1s" # set timeout_commit to five minutes, timeout_commit helps in delaying time between blocks
      # it tells how long we wait after committing block , before starting new height